# Generated by Django 6.1 on 2026-09-01 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the department.', max_length=255, unique=True, verbose_name='Department Name')),
                ('code', models.CharField(help_text='Short code (e.g., CS for Computer Science).', max_length=20, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g., Semester One).', max_length=100, verbose_name='Semester Name')),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024/2025).', max_length=20, verbose_name='Academic Year')),
                ('semester_number', models.IntegerField(choices=[(1, 'Semester One'), (2, 'Semester Two')], default=1, verbose_name='Semester Number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, help_text='Mark as active for current semester.', verbose_name='Is Active')),
                ('is_result_published', models.BooleanField(default=False, help_text='Mark when results are published for viewing.', verbose_name='Is Result Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['academic_year', 'semester_number'],
                'unique_together': {('academic_year', 'semester_number')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique course code (e.g., CS101).', max_length=20, unique=True, verbose_name='Course Code')),
                ('title', models.CharField(help_text='Full course title.', max_length=255, verbose_name='Course Title')),
                ('credit_units', models.IntegerField(help_text='Number of credit units (1-6).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Credit Units')),
                ('year_of_study', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], default=1, verbose_name='Year of Study')),
                ('is_elective', models.BooleanField(default=False, help_text='Mark if this is an elective course.', verbose_name='Is Elective')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department', verbose_name='Department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.semester', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
    ]
